name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install llvm
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "10.0"
    - name: checkout repository
      uses: actions/checkout@v2
    - name: build unit tests
      run: make build LLVM_PATH=${{ env.LLVM_PATH }}/
    - name: run unit tests
      run: make test